/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedJobAnalysisRouteImport } from './routes/_authenticated/job-analysis'
import { Route as AuthenticatedHoneypotsRouteImport } from './routes/_authenticated/honeypots'
import { Route as AuthenticatedHiddenGemsRouteImport } from './routes/_authenticated/hidden-gems'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobAnalysisRoute =
  AuthenticatedJobAnalysisRouteImport.update({
    id: '/job-analysis',
    path: '/job-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHoneypotsRoute = AuthenticatedHoneypotsRouteImport.update({
  id: '/honeypots',
  path: '/honeypots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHiddenGemsRoute = AuthenticatedHiddenGemsRouteImport.update({
  id: '/hidden-gems',
  path: '/hidden-gems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/hidden-gems': typeof AuthenticatedHiddenGemsRoute
  '/honeypots': typeof AuthenticatedHoneypotsRoute
  '/job-analysis': typeof AuthenticatedJobAnalysisRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/hidden-gems': typeof AuthenticatedHiddenGemsRoute
  '/honeypots': typeof AuthenticatedHoneypotsRoute
  '/job-analysis': typeof AuthenticatedJobAnalysisRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/hidden-gems': typeof AuthenticatedHiddenGemsRoute
  '/_authenticated/honeypots': typeof AuthenticatedHoneypotsRoute
  '/_authenticated/job-analysis': typeof AuthenticatedJobAnalysisRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/callback'
    | '/analytics'
    | '/compare'
    | '/config'
    | '/dashboard'
    | '/export'
    | '/hidden-gems'
    | '/honeypots'
    | '/job-analysis'
    | '/rankings'
    | '/workspace'
    | '/auth/callback'
    | '/candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/callback'
    | '/analytics'
    | '/compare'
    | '/config'
    | '/dashboard'
    | '/export'
    | '/hidden-gems'
    | '/honeypots'
    | '/job-analysis'
    | '/rankings'
    | '/workspace'
    | '/auth/callback'
    | '/candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/callback'
    | '/_authenticated/analytics'
    | '/_authenticated/compare'
    | '/_authenticated/config'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/hidden-gems'
    | '/_authenticated/honeypots'
    | '/_authenticated/job-analysis'
    | '/_authenticated/rankings'
    | '/_authenticated/workspace'
    | '/auth/callback'
    | '/_authenticated/candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-analysis': {
      id: '/_authenticated/job-analysis'
      path: '/job-analysis'
      fullPath: '/job-analysis'
      preLoaderRoute: typeof AuthenticatedJobAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/honeypots': {
      id: '/_authenticated/honeypots'
      path: '/honeypots'
      fullPath: '/honeypots'
      preLoaderRoute: typeof AuthenticatedHoneypotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hidden-gems': {
      id: '/_authenticated/hidden-gems'
      path: '/hidden-gems'
      fullPath: '/hidden-gems'
      preLoaderRoute: typeof AuthenticatedHiddenGemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedHiddenGemsRoute: typeof AuthenticatedHiddenGemsRoute
  AuthenticatedHoneypotsRoute: typeof AuthenticatedHoneypotsRoute
  AuthenticatedJobAnalysisRoute: typeof AuthenticatedJobAnalysisRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedHiddenGemsRoute: AuthenticatedHiddenGemsRoute,
  AuthenticatedHoneypotsRoute: AuthenticatedHoneypotsRoute,
  AuthenticatedJobAnalysisRoute: AuthenticatedJobAnalysisRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
